backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/images"
public_folder: "/assets/images"
collections:
  - name: "chapters"
    label: "Chapters"
    folder: "src/chapters"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Chapter Title", name: "title", widget: "string" }
      - { label: "Date(TOC Order)", name: "date", widget: "datetime" }
      - { label: "Thumbnail Image", name: "image", widget: "image" }
      - label: "Chapter Content"
        name: "contents"
        widget: "list"
        types:
          - label: "Section"
            name: "section"
            widget: "object"
            fields:
              - { label: "Section Title", name: "sectiontitle", widget: "string" }
              - { label: "Large Text", name: "largetext", widget: "markdown" }
              - { label: "Small Text", name: "smalltext", widget: "markdown" }
              - { label: "Large Image", name: "largeimage", widget: "image" }