backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/images"
public_folder: "/assets/images"
collections:
  - name: "chapters"
    label: "Chapters"
    folder: "src/chapters"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Chapter Title", name: "title", widget: "string" }
      - { label: "Date(TOC Order)", name: "date", widget: "datetime" }
      - { label: "Thumbnail Image", name: "image", widget: "image" }
      - label: "Chapter Content"
        name: "contents"
        widget: "list"
        types:
          - label: "Section"
            name: "section"
            widget: "object"
            fields:
              - { label: "Section Title", name: "string", widget: "markdown" }
              - label: "Section Content"
                name: "sectioncontent"
                widget: "list"
                types:
                  - label: "Large Text"
                    name: "largetext"
                    widget: "object"
                    fields:
                      - { label: "Enter Text", name: "string", widget: "markdown"}
                  - label: "Body Text"
                    name: "bodytext"
                    widget: "object"
                    fields:
                      - { label: "Enter text", name: "string", widget: "markdown" }
                      - label: "Align Content"
                        name: "align"
                        widget: "select"
                        options: ["left", "center", "right"]
                  - label: "Image"
                    name: "inlineimage"
                    widget: "object"
                    fields:
                      - { label: "Image", name: "image", widget: "image" }
                      - label: "Align Content"
                        name: "align"
                        widget: "select"
                        options: ["left", "center", "right"]
          - label: "Full Bleed Image"
            name: "fbimage"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }