backend:
  name: git-gateway
  branch: main
media_folder: "_site/assets/images"
public_folder: "/assets/images"
collections:
  - name: "chapters"
    label: "Chapters"
    folder: "src/chapters"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Chapter Title", name: "title", widget: "string" }
      - { label: "Date(TOC Order)", name: "date", widget: "datetime" }