backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/images"
public_folder: "/assets/images"
collections:
  - name: "chapters"
    label: "Chapters"
    folder: "src/chapters"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Chapter Title", name: "title", widget: "string" }
      - { label: "Date(TOC Order)", name: "date", widget: "datetime" }
      - { label: "Thumbnail Image", name: "image", widget: "image" }
      - label: "Chapter Content"
        name: "contents"
        widget: "list"
        types:
          - label: "Section Title"
            name: "sectiontitle"
            widget: "object"
            fields:
              - { label: "Enter section title", name: "string", widget: "string" }
          - label: "Large Text"
            name: "largetext"
            widget: "object"
            fields:
              - { label: "Enter Text", name: "string", widget: "string"}
          - label: "Small Text"
            name: "smalltext"
            widget: "object"
            fields:
              - { label: "Enter text", name: "string", widget: "string" }
          - label: "Large Image"
            name: "largeimage"
            widget: "object"
            fields:
              - { label: "Large Image", name: "image", widget: "image" }