backend:
  name: git-gateway
  branch: main
media_folder: "_site/assets/images"
public_folder: "/assets/images"
collections:
  - name: "chapters"
    label: "Chapters"
    folder: "src/chapters"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Chapter Title", name: "title", widget: "string" }
      - { name: "order", label: "Order", widget: "number" }
      - { label: "Thumbnail Image", name: "image", widget: "image" }
      - label: "Chapter Content"
        name: "contents"
        widget: "list"
        types:
          - label: "Large Text"
            name: "largetext"
            widget: "object"
            fields:
              - { label: "Enter Text", name: "string", widget: "string"}
          - label: "Small Text"
            name: "smalltext"
            widget: "object"
            fields:
              - { label: "Enter text", name: "string", widget: "string" }
    sort: [{ field: "order", numeric: true, direction: "asc" }]
